apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fa3v
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0019-tenant/ci1t-43256-0019-app/devfile-sample-fa3v@sha256:3048c30ea1e9f41577065e231a314a913a3125fdfda4a67a93c0b4bce8b43833
        name: my-nodejs
        resources: {}
status: {}
